### ISSUE TITLE
Messages won't send through in builds exported without debug

### ISSUE THREAD

**Issue by zyq0825** [ASecondGuy/BugReporter#4]
Operating system: Windows 10 and Windows 11
Godot version: 3.5.3 stable

I've encountered an issue where messages won't send through in builds exported without debug, without any error messages. Exporting with debug enabled resolved the issue, but now we are working on a Mac build for our game. It seems that GodotSteam won't work for Mac if exported with debug, so we have to uncheck that option.
Below are my codes for the reporter node, modified from your original codes. Thank you for your excellent work.

```
extends NinePatchRect

export var cfg_path := "res://addons/BugReporter/config.cfg"
export var hide_after_send := true
export var clear_after_send := true
 
const
var _cfg : ConfigFile

onready var _screenshot := $"%Screenshot"
onready var _screenshot_check = $MarginContainer/VBox/CheckBox
onready var _mail : LineEdit = $MarginContainer/VBox/Mail/LineEdit
onready var _http := $HTTPRequest
onready var _send_button = $MarginContainer/VBox/SendButton
onready var message_window = $"%Message"
onready var timer = $Timer
onready var notice = $"%Notice"

func _ready():
	_cfg = ConfigFile.new()
	var err := _cfg.load(cfg_path)
	if err != OK:
		push_error("Bugreporter couldn't load config. Reason: %s" % err)
	var img := get_viewport().get_texture().get_data()
	img.flip_y()
	var text := ImageTexture.new()
	text.create_from_image(img)
	_screenshot.texture = text

func _on_SendButton_pressed():
	timer.start()
	if _http.get_http_client_status() != HTTPClient.STATUS_DISCONNECTED:
		return

	var message : String = message_window.text.replace("```", "")
	var player_id := "playerid: %s" % _unique_user_id()
	if _cfg.get_value("webhook", "anonymous_players", false):
		player_id = "anonymous"
	var contact_info := _mail.text.dedent()

	var request_body := []# 1st place is reserved for json_payload
	var json_payload := {
		"username" : "%s:" % _get_game_name(),
		"tts" : _cfg.get_value("webhook", "tts", false),
	}
	var embed = {
			"title": "Bug reported by %s" % [player_id],
			"color": _cfg.get_value("webhook", "color", 15258703),
		}
	var fields := []

	if !contact_info.empty():
		fields.push_back({
				"name" : "Contact Info:",
				"value" : contact_info
		})

	if !message.empty():
		fields.push_back({
				"name" : "Message:",
				"value" : "```\n%s\n```" % message,
			}
	)

	if _screenshot_check.pressed:
		embed["image"] = {
					"url" : "attachment://screenshot0.png",
				}

		request_body.push_back(_screenshot.texture)

	embed["fields"] = fields
	json_payload["embeds"] = [embed]

	request_body.push_front(json_payload)
	request_body.push_back("user://logs/godot.log")
	var payload := _array_to_form_data(request_body)

	if fields.empty():
		return

	_http.request(_cfg.get_value("webhook", "url", ""), 
			PoolStringArray(["connection: keep-alive", "Content-type: multipart/form-data; boundary=boundary"]), 
			true, 
			HTTPClient.METHOD_POST,
			payload
	)
	_send_button.disabled = true
func _on_HTTPRequest_request_completed(result, response_code, headers, body):
	_send_button.disabled = false
	if clear_after_send:
		_mail.clear()
		message_window.text = ""
	if hide_after_send:
		queue_free()
func _unique_user_id() -> String:
	return str(hash(str(OS.get_unique_id(), "|", _get_game_name())))
func _get_game_name():
	return _cfg.get_value("webhook", "game_name")
func _texture_to_png_bytes(texture : Texture, max_size:=8000000)->PoolByteArray:
	var img := texture.get_data()
	var bytes : PoolByteArray = img.save_png_to_buffer()
	
	while bytes.size() > max_size:
		img.resize(img.get_width()/2, img.get_height()/2)
		bytes = img.save_png_to_buffer()
	return bytes
func _array_to_form_data(array:Array)->String:
	var file_counter := 0
	var output = ""
	for element in array:
		output += "--boundary\n"
		if element is Dictionary:
			output += 'Content-Disposition: form-data; name="payload_json"\nContent-Type: application/json\n\n'
			output += to_json(element) + "\n"
		elif element is Texture:
			output += 'Content-Type: image/png; name="files[%s]"\n' % file_counter
			output += 'Content-Disposition: attachment; filename="screenshot%s.png"\n' % file_counter
			output += 'Content-Transfer-Encoding: base64\nX-Attachment-Id: f_ljiz6nfz0\nContent-ID: <f_ljiz6nfz0>'
			output += "\n\n"
			output += Marshalls.raw_to_base64(_texture_to_png_bytes(element)) + "\n"
			file_counter += 1
		elif element is String:
			var f = File.new()
			if f.open(element, File.READ) == OK:
				var file = f.get_as_text()
				f.close()
				if !file.empty():
					output += 'Content-Type: plain/text"\n'
					output += 'Content-Disposition: attachment; filename="log"; name="files[%s]";\n' %file_counter
					output += "\n"
					output += file
			else:
				printerr("BugReporter could not attach File %s to Message" % element)
			file_counter+=1
	output += "--boundary--"
	return output
func _on_Close_pressed():
	queue_free()
func _on_Timer_timeout():
	print("http connecting result:",_http.get_http_client_status())
```

**Comment by ASecondGuy** [comment]
Don't share your webhook url it can lead to data leaks. For testing it is fine to use it but for release, you should use a proxy.

It works for me with debug and without. Did you maybe forget to include the config.cfg in release builds?

**Comment by zyq0825** [comment]
> Don't share your webhook url it can lead to data leaks. For testing it is fine to use it but for release, you should use a proxy.
> 
> It works for me with debug and without. Did you maybe forget to include the config.cfg in release builds?

Thanks for the reminder! 
I did include the config.cfg file as you can see I loaded it in the _ready() function and I didn't get any error. I wonder if this has something to do with GodotSteam. I'll test this in a new project and let you know. Thanks for your reply!

**Comment by zyq0825** [comment]
I tested it in a new project. Didn't work if exported without debug...I also tried to turn off the embed PCK option, but it didn't seem to matter. Here's my export settings: 
![屏幕截图 2024-05-27 101747](https://github.com/ASecondGuy/BugReporter/assets/46349039/43d84d8d-111a-4c05-8c99-2118ab7fa6d1)
![屏幕截图 2024-05-27 101827](https://github.com/ASecondGuy/BugReporter/assets/46349039/de8c7774-ef6d-4bdd-80c8-554fbbe33ed5)
Please let me know if you need more information.

**Comment by ASecondGuy** [comment]
Still can't reproduce it.
Maybe your firewall blocks the release build but not debug builds?
If that is the case it would fail without error message.
If you look at result and response_code in this function
`func _on_HTTPRequest_request_completed(result, response_code, headers, body):`
it might tell you what exactly is wrong.

**Comment by ASecondGuy** [comment]
I just backported the new features and added the missing error message so if you update you should get an error.

**Comment by zyq0825** [comment]
Thanks for that! I tried the new version and I got:

BugReporter message send
BugReporter Error sending Report. Result: 0 Responsecode: 400 Body: {"message": "Cannot send an empty message", "code": 50006}

But I did add a message though. "build test" specifically. And in the editor, even if I don't write anything, the message can be sent through.

**Comment by ASecondGuy** [comment]
It seems that the request payload is somehow getting messed up.
Can you add `print(payload)` on line 175 in webhook_builder.gd and tell me what it prints?
When you only send a message it should look something like this:
```
--b4174803096
Content-Disposition: form-data; name="payload_json"
Content-Type: application/json

{"attachments":[],"embeds":[{"color":15258703,"fields":[{"inline":false,"name":"Message:","value":"```\ntest\n```"}],"title":"Bugreport by playerid: 149521579"}],"tts":false,"username":"BugReporter:"}
--b4174803096--
```
If it looks like that then I have no idea what else it could be.
You can change the URL to `https://discord.com/api/v10/webhooks/...` to get a better error message from Discord. That might help as well.

**Comment by zyq0825** [comment]
I found out what's wrong! When I send a message with no attachment, it'll send through. But not the ones with analytics. I get: 

```
--b1299572883
Content-Disposition: form-data; name="payload_json"
Content-Type: application/json

{"attachments":[{"id":0}],"embeds":[{"color":15258703,"fields":[{"inline":false,"name":"Message:","value":"```\nbuild test with log\n```"}],"title":"Bugreport by playerid: 2078827880"}],"tts":false,"username":"From Soil to Bottle:"}
--b1299572883
--b1299572883--
BugReporter message send
BugReporter Error sending Report. Result: 0 Responsecode: 400 Body: {"message": "Cannot send an empty message", "code": 50006}
```

**Comment by ASecondGuy** [comment]
It seems there is some invalid data in _request_body.
That way there are 2 boundaries right next to each other making the request invalid.
Can you replace the print with `print(_request_body)` and tell me what it prints?

**Comment by ASecondGuy** [comment]
Ok. I found and fixed a bug that caused this exact problem when you tried to send the log file (Or any file after the first send).
But You didn't send log files at the start so I'm not sure if that will fix your problem.

**Comment by zyq0825** [comment]
Ohhhh it works now. Thank you very much!
